default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: MyStr0ngP@ss!
  socket: /var/run/mysqld/mysqld.sock
  host: localhost

development:
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: MyStr0ngP@ss!
  socket: /var/run/mysqld/mysqld.sock
  host: localhost
  database: my_app_development

test:
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: MyStr0ngP@ss!
  socket: /var/run/mysqld/mysqld.sock
  host: localhost
  database: my_app_test

production:
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: MyStr0ngP@ss!
  socket: /var/run/mysqld/mysqld.sock
  host: localhost
  database: todo-users
